version: "3.7"
services:
  gateway:
    build:
      context: gateway/docker
      dockerfile: dev/nginx/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - frontend
      - api

  frontend:
    build:
        context: frontend/docker
        dockerfile: dev/nginx/Dockerfile
    volumes:
      - ./frontend:/app

  api:
    build:
        context: api/docker
        dockerfile: dev/nginx/Dockerfile
    volumes:
      - ./api:/app
    depends_on:
      - api-php-fpm

  api-php-fpm:
    build:
      context: api/docker
      dockerfile: dev/php-fpm/Dockerfile
    environment:
        APP_ENV: dev
        DEBUG_MODE: 1
        PHP_IDE_CONFIG: serverName=API
    volumes:
      - ./api:/app

  api-php-cli:
    build:
        context: api/docker
        dockerfile: dev/php-cli/Dockerfile
    volumes:
        - ./api:/app