auction:
	ansible-playbook -i hosts.yml auction.yml -v

renew-certificates:
	ansible-playbook -i hosts.yml renew-certificates.yml -v

authorize:
	ansible-playbook -i hosts.yml authorize.yml  -v

docker-login:
	ansible-playbook -i hosts.yml docker-login.yml -v
