auction:
	ansible-playbook -i hosts.yml auction.yml -vv

renew-certificates:
	ansible-playbook -i hosts.yml renew-certificates.yml -vv

authorize:
	ansible-playbook -i hosts.yml authorize.yml -vv

docker-login:
	ansible-playbook -i hosts.yml docker-login.yml -vv